name: Publish VSCode Extension
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish extension
        run: vsce publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
